import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import WalletComponent from "~/components/WalletComponent";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Create <span className={styles.pinkSpan}>T3</span> App
          </h1>
          <div className={styles.cardRow}>
              <WalletComponent/>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
